services:
    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_init:
        class: Setono\SyliusFacebookTrackingPlugin\EventListener\FacebookTrackingEventListener
        arguments:
            - 'SetonoSyliusFacebookTrackingPlugin::facebook_pixel_init.html.twig'
            - "@setono_sylius_facebook_tracking_plugin.context.config"
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_add_payment_info:
        class: Setono\SyliusFacebookTrackingPlugin\EventListener\AddPaymentInfoEventListener
        arguments:
            - "@session"
        tags:
            - { name: kernel.event_listener, event: sylius.order.post_payment, method: addPaymentInfo }

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_add_to_cart:
        class: Setono\SyliusFacebookTrackingPlugin\EventListener\AddToCartEventListener
        arguments:
            - "@session"
        tags:
            - { name: kernel.event_listener, event: sylius.order_item.post_add, method: addToCart}

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_initiate_checkout:
        class: Setono\SyliusFacebookTrackingPlugin\EventListener\InitiateCheckoutEventListener
        arguments:
            - "@session"
        tags:
            - { name: kernel.event_listener, event: sylius.order.pre_address, method: initiateCheckout }

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_purchase:
        class: Setono\SyliusFacebookTrackingPlugin\EventListener\PurchaseEventListener
        arguments:
            - "@session"
        tags:
            - { name: kernel.event_listener, event: sylius.order.post_complete, method: purchase }

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_view_content:
        class: Setono\SyliusFacebookTrackingPlugin\EventListener\ViewContentEventListener
        arguments:
            - "@session"
        tags:
            - { name: kernel.event_listener, event: sylius.product.show, method: viewContent }
