services:
    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_init:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
#        class: Setono\SyliusFacebookTrackingPlugin\EventListener\FacebookTrackingEventListener
        arguments:
            - 'SetonoSyliusFacebookTrackingPlugin::facebook_pixel_init.html.twig'
            - "@setono_sylius_analytics_plugin.context.config"
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_add_payment_info:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusFacebookTrackingPlugin::FacebookEvents\AddPaymentInfo.html.twig'
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.checkout.select_payment.before_form, method: onBlockEvent }

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_add_to_cart:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusFacebookTrackingPlugin::FacebookEvents\AddToCart.html.twig'
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.after_add_to_cart, method: onBlockEvent }

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_initiate_checkout:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusFacebookTrackingPlugin::FacebookEvents\InitiateCheckout.html.twig'
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.checkout.address.after_header, method: onBlockEvent }

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_purchase:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusFacebookTrackingPlugin::FacebookEvents\Purchase.html.twig'
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.order.thank_you.after_message, method: onBlockEvent }

    setono_sylius_facebook_tracking_plugin.event_listener.facebook_tracking_view_content:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusFacebookTrackingPlugin::FacebookEvents\ViewContent.html.twig'
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.cart.summary.after_content_header, method: onBlockEvent }
