services:
  setono_sylius_facebook_tracking_plugin.listener.javascript:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
    - '@SetonoSyliusFacebookTrackingPlugin/Admin/_javascripts.html.twig'
    tags:
    - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.layout.javascripts, method: onBlockEvent }
