services:
    setono_sylius_facebook_tracking_plugin.listener.menu.facebook_config:
        class: Setono\SyliusFacebookTrackingPlugin\Menu\FacebookTrackingMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addFacebookTracking}
        arguments:
            - "@setono_sylius_facebook_tracking_plugin.context.config"