services:
    setono_sylius_facebook_tracking_plugin.facebook_config_rule_checker.facebook_config_rule:
        class: Setono\SyliusFacebookTrackingPlugin\Checker\Rule\FacebookConfigRuleChecker
        arguments:
            - "@sylius.repository.facebook"
        tags:
            - { name: setono_sylius_facebook_tracking_plugin.facebook_config_rule_checker,
                type: facebook_config,
                label: setono_sylius_facebook_tracking_plugin.facebook_config_rule.facebook_config,
                form_type: Setono\SyliusFacebookTrackingPlugin\Form\Type\FacebookConfigRuleType
              }

