sylius_resource:
    resources:
        setono_sylius_facebook_tracking_plugin.facebook_config:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusFacebookTrackingPlugin\Model\FacebookConfig
                interface: Setono\SyliusFacebookTrackingPlugin\Model\FacebookConfigInterface
                repository: Setono\SyliusFacebookTrackingPlugin\Repository\FacebookConfigRepository
                form: Setono\SyliusFacebookTrackingPlugin\Form\Type\FacebookConfigType
