sylius_resource:
    resources:
        setono_sylius_facebook_tracking_plugin.facebook_config:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusFacebookTrackingPlugin\Entity\FacebookConfig
                interface: Setono\SyliusFacebookTrackingPlugin\Entity\FacebookConfigInterface
                repository: Setono\SyliusFacebookTrackingPlugin\Repository\FacebookConfigRepository
            translation:
                classes:
                    model: Setono\SyliusFacebookTrackingPlugin\Entity\FacebookConfigTranslation
                    interface: Setono\SyliusFacebookTrackingPlugin\Entity\FacebookConfigTranslationInterface
