sylius_fixtures:
    suites:
        default:
            fixtures:

                setono_facebook_pixel:
                    options:
                        custom:
                            fake_pixel_active:
                                pixel_id: 1234567
                                enabled: true
                                channels:
                                    - 'FASHION_WEB'
                            fake_pixel_disabled:
                                pixel_id: '12345678'
                                enabled: false
                                channels:
                                    - 'FASHION_WEB'
                            fake_pixel_no_channels:
                                pixel_id: 123456789
