setono_sylius_facebook_tracking_plugin_admin_facebook_config:
    resource: |
        section: admin
        alias: setono_sylius_facebook_tracking.facebook_config
        templates: SetonoSyliusFacebookTrackingPlugin:Crud
        except: ['create', 'delete']
        permission: true
        redirect: update
        vars:
            all:
               templates:
                   form: "@SetonoSyliusFacebookTrackingPlugin/FacebookConfig/Crud/_form.html.twig"
                   breadcrumb: "@SetonoSyliusFacebookTrackingPlugin/FacebookConfig/Crud/_breadcrumb.html.twig"
    type: sylius.resource
